# Generated by Django 2.2.6 on 2019-11-05 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_cnt', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('application_format', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='SITHUMB.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='SITHUMB.Activity')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='SITHUMB.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('transcript_format', models.TextField(default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SITHUMB.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='SITHUMB.Activity')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='SITHUMB.Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='examiners',
            field=models.ManyToManyField(to='SITHUMB.Examiner'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='SITHUMB.Activity')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='SITHUMB.Candidate')),
            ],
        ),
    ]
