# Generated by Django 2.2.6 on 2019-12-02 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('section_cnt', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('application_format', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('student_id', models.CharField(default='', max_length=100)),
                ('wx_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=0)),
                ('compulsory', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('transcript_format', models.TextField(default='')),
                ('examinees', models.TextField(default='')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SITHUMB.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=256)),
                ('examinees', models.TextField(default='')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='SITHUMB.Activity')),
                ('sections', models.ManyToManyField(to='SITHUMB.Section')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted', models.BooleanField(default=False)),
                ('stage', models.IntegerField(default=0)),
                ('application_form', models.TextField(default='')),
                ('transcript', models.TextField(default='')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='SITHUMB.Activity')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='SITHUMB.Candidate')),
            ],
        ),
    ]
