# Generated by Django 2.2.6 on 2019-11-05 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITHUMB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL),
        ),
    ]
