# Generated by Django 2.2.6 on 2019-11-05 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITHUMB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='SITHUMB.Activity'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='SITHUMB.Candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='SITHUMB.Activity'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='examiners',
            field=models.ManyToManyField(null=True, to='SITHUMB.Examiner'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='SITHUMB.Activity'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiners', to='SITHUMB.Section'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SITHUMB.Activity'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='SITHUMB.Activity'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='SITHUMB.Candidate'),
        ),
    ]
