# Generated by Django 2.2.6 on 2019-11-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITHUMB', '0002_auto_20191105_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='transcript_format',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='activity',
        ),
        migrations.AddField(
            model_name='examiner',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SITHUMB.Activity'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('transcript_format', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SITHUMB.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='examiner',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SITHUMB.Section'),
            preserve_default=False,
        ),
    ]
