# Generated by Django 2.2.6 on 2019-11-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITHUMB', '0003_auto_20191105_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='form',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='transcript_format',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='form',
            field=models.TextField(default=''),
        ),
    ]
