# Generated by Django 2.2.6 on 2019-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITHUMB', '0005_auto_20191105_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='section_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='section',
            name='to_date',
            field=models.DateField(default=None),
        ),
    ]
